[package]
name = "tcp_proxy"
version = "0.1.0"
authors = ["Sergei Fomin <sergio-dna@yandex.ru>"]
edition = "2021"

[dependencies]
clap = { version = "3.1.15", features = ["derive"] }
log = "0.4"
rand = "0.8.5"
simplelog = "0.12.0"
