[package]
name = "comm"
version = "0.1.0"
authors = ["Sergei Fomin <sergio-dna@yandex.ru>"]
edition = "2021"

[dev-dependencies]
pretty_assertions = ">= 1.1.0"
rand = ">= 0.8.4"
tempfile = ">= 3.3.0"
