peer_service:
  dial_cooldown: 3s
  listen_address: localhost:9090
  dial_addresses: []
gossip_service:
  eager_requests_interval: 10s
mining_service:
  thread_count: 1
  max_tx_per_block: 10
  public_key: "MIICIDALBgkqhkiG9w0BAQEDggIPADCCAgoCggIBALxKt7onRkrDCXqAypnqbmqk+xQbvJfAxW/mhifdC4at4KpXa2jQhjCL9mtmLqK6TEtFKsD+KmcGUJ9ww9SddnhT9cZgb6lZ6p0e1JhJwXzCiuz0ft8F7tFVbKG2DE3lLWYNu7d/fozC8v2gPvqknzhJLTjMDbdGriXrQCesGsj7YJvE2Je72GXNfcgq/y1ZwPKcYzpuetNgQupXckmgLFqsXAuqinruPxHA2RzqxD+CTUMZX7UGuH/cjJmneb2hPYtzvXHOycWBmOuQ28zDTTebepXIyTKZw355iJl+x/SYg/++ja5tIRnD+djxSF5DqRrcnertEbg7ugjXPx2EJSghI0ulZADA5/Y26VyfzeN259lm+VVQrlcKcg/DD9m6mIFjxfmOTZwaom74Kpkbbi4IBzxAqwZW5/L/Sl6ZJH9y3Ucw6zlIL66H/7qpGMsVQtlO+1RZxem3y9CIKvavuhpsiokqhnwglzXBamb/i7M6j5/3xXsZ5RIFH4dzyv/pCw7xIqUCPchPNNEaIcGn+6PoleoXZB0bXCnSnYHlnnC2oABUv8bmy4DF8xDzG6sWlM9UNY9V+wmKnxALm1cvRImnq6L6rjwDZMXvWNioZDFlgXd6O+ThGiXUNAArhv4+VOv2yrui7wLgnvhtmmWnSCgtIH85nlX1PO9j0osJX3k1AgMBAAE="