[package]
name = "flatmap"
version = "0.1.0"
authors = ["Sergei Fomin <sergio-dna@yandex.ru>"]
edition = "2021"

[dependencies]
criterion = ">= 0.3.5"
pretty_assertions = ">= 1.2.0"
rand = ">= 0.8.5"

[[bench]]
name = "benches"
harness = false
